#ifndef INIT_SMOTOR_H
#define INIT_SMOTOR_H

#include "SMotor.h"

#define YAW_SMOTOR_PWM_TIMER &htim2
#define YAW_SMOTOR_PWM_CHANNEL TIM_CHANNEL_1
#define YAW_SMOTOR_DIR_PORT DIR_GPIO_Port
#define YAW_SMOTOR_DIR_PIN DIR_Pin
#define YAW_SMOTOR_ANTI_DIR GPIO_PIN_SET

#define PITCH_SMOTOR_PWM_TIMER &htim2
#define PITCH_SMOTOR_PWM_CHANNEL TIM_CHANNEL_2
#define PITCH_SMOTOR_DIR_PORT DIR_GPIO_Port
#define PITCH_SMOTOR_DIR_PIN DIR_Pin
#define PITCH_SMOTOR_ANTI_DIR GPIO_PIN_RESET



#endif // INIT_SMOTOR_H